name: CICD

on:
  push:
    tags:
      - 'v*'

jobs:
  # check:
  #   runs-on: ubuntu-latest
  #   services:
  #     redis:
  #       image: redis
  #       ports:
  #         - 6379:6379
  #       options: --entrypoint redis-server
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v3

  #     - name: Init rust envrionment
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #         components: rustfmt, clippy

  #     - name: Cache rust
  #       uses: Swatinem/rust-cache@v2

  #     - name: Check format
  #       run: cargo fmt --all -- --check

  #     - name: Check clippy
  #       run: cargo clippy --all --all-features

  #     - name: Run test
  #       run: cargo test --all-features

  #     - name: Upload to codecov.io
  #       uses: codecov/codecov-action@v2
  #       with:
  #         token: ${{secrets.CODECOV_TOKEN}}

  #     - name: Archive code coverage results
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: code-coverage-report
  #         path: cobertura.xml

  release:
#    if: startsWith(github.ref, 'refs/tags/')
#    needs: [check]
    strategy:
      matrix:
        os:
          - name: ubuntu
            host: ubuntu-latest
    runs-on: ${{ matrix.os.host }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Init rust envrionment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Prepare Artifact
        shell: bash
        run: |
          mkdir ./bin
          cp ./target/release/action-test ./bin/action-test-${{ matrix.os.name }}

      - name: Prepare Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./bin/

      # - name: Upload Artifact to Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       *.tar.gz
      #       *.txt
